### ISSUE TITLE
[RFE] Configuration file parsing

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#372]
**Is your feature request related to a problem? Please describe.**

At the moment the current configuration parsing uses the standard YAML decoder plus some tweaks to establish sane defaults, it's not the best of the solutions so I think we could start working on other approaches.

**Describe the solution you'd like**
The [viper](https://github.com/spf13/viper) library provides some interesting features such as reading from environment variables, settings defaults and more. I proposed this library as an alternative b/c is the one I'm more familiar with, but there's not any hard requirement to use it.

**Comment by smalleni** [comment]
@vishnuchalla This seems like a good task for Shashank, thoughts?

**Comment by vishnuchalla** [comment]
Yes. Should to be decent one to explore viper.

**Comment by shashank-boyapally** [comment]
By exploring viper, we see that we can use setDefault method to set defaults for the unset parameters, but looking deeper into it we understand we couldn't set defaults for the slice of objects using viper. In order to tackle this issue I'm checking if the param is set or not, and if not I'm assigning a default value which we need. This process could only be done after Unmarshaling to the configSpec. The following are the drawbacks which I felt:

- Since we are cannot use setDefault method, viper is only being used to read the config(this too partially) and unmarshal it to a struct.
- The major idea to shift from yamlv3 to viper is to set defaults which is not possible at the moment.
- Using viper for Unmarshaling and reading and performing the loop operation to check of set of param? is costly which inturn decreases our efficiency. 
- We cannot override the Unmarshal method of viper.

Since yamlv3 now preserves the ordering of the objects, and Unmarshal method  can be overridden where we could set defaults, I feel the present way is the most optimal approach for the time being. Please let me know any of your thoughts over this.
